cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    yjhp1016:
      email:yjhp1016@gmail.com 
      name: jianhui
      password: $2b$12$9.ggJiqwa7yTc/x8n7xoIeLSipvMLQ7OOKUNXinBUQtm5kAC9n.xy # To be replaced with hashed password
    leo200809:
      email: liang185954@gmail.com
      name: liang
      password: $2b$12$CNoj4Yy9Al8Fscvjt0B7Z.5mgH0TN0GHpo1HndsJlJOBrYtBctzvu # To be replaced with hashed password
preauthorized:
  emails:
  - none@none
